### ISSUE TITLE
Roadmap 2019-08-18

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#67]
Roadmap
=======

Because when I submit a pull request the changes are a surprise, I'd like to keep a roadmap so we can expect changes.

Where are we now?
----------------

Through the course of documenting the application I've made changes like 
plurality and removing aliases.  I needed to remove these in order to 
understand and then document why these existed in the application.  Now that
I've groked the code I have documented the reason for aliases
and other parts I didn't understand before.

Check out the analytics on google :)  The average docs session duration
is > 7:00!  That means people are taking the time to read them.  Since I came on
the project we've had 8 new stars and 2 forks.  

Future Changes 
--------------

- [x] Merge refactor #2 and path-alias docs

- [x] Add aliases back into code
    With the documentaion understanding how these work means we can use them    

- [x] Reintroduce plurality for modules 

- [x] Rename Directory Structures to Directory Structure Parts because they are all
  optional
  
- [x]  Consider multiple directory tree structures.  The default and recommended 
  structure will be that of the application.  But I've seen other good structures
  which use the same building blocks of media, core, data, layout, module, shared, 
  and sytles/themes.  In Additional Resources we could have pages for each tree
  structure as alternatives.  It is my hope we can pull in some of the other 
  repositories which also define a directory structure and include that structure
  as part of angular-folder-structure

**Comment by mathisGarberg** [comment]
Adding a road-map to keep track and discuss further changes sounds like a good addition. This will help other people comment on further releases and understand the reasoning behind why it's implemented.

The implementation of `readthedocs` has really taken everything to another level. The organization and structure is more clear and beginner friendly than ever. That the average is greater than 7:00 is awesome and the increase in stars and forks is proof that people agree.

### Comments
* I will review the incoming PRs when I get back from work.
* Adding aliases change back to plurality is probably the best way to go. I have mixed opinions on what the best solution might be, but I reviewed the issues related to this and agree.
* The suggestion of leaving a page with links to other structures sounds like a good addition. When I did the research for the article that inspired this project, I focused on a scalable, multiple module architecture. But I also ended up referring to other GitHub repositories with another structure in place.

### Questions
* Does renaming Directory Structure to Directory Structure Parts suggests the optional behavior of adding the `Parts` of the project the user see fit?

**Comment by TomHAnderson** [comment]
Directory Structure Parts
==================

After studying other "best practice" repos I feel the parts of this project's directory structure are common and their placement becomes more of a defining factor.  As a developer I should have the choice to install each part such as no media directory & no data directory, but all the rest.

So, yes, I want users to understand what we are suggesting and I want us to suggest where to put the parts, but I don't want a hard-and-true one-way to do it.  I want flexibility to implement just the parts your application would benefit from and I want users to throughly understand the reasoning for each part.

**Comment by mathisGarberg** [comment]
We can probably create something like the [ngx-rocket-Generatpr](https://github.com/ngx-rocket/generator-ngx-rocket) with options for your desired structure.

**Comment by TomHAnderson** [comment]
As we finish the list of each Roadmap post, I'll check them off one at a time.  When they are all done I'll close the Roadmap and create a new one when I'm ready to plan more.

I've renamed this to the date I created it so we can have multiple roadmaps; like sprints.
