### ISSUE TITLE
Roadmap 2019-08-20

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#74]
- [x] Compile a better list of alternative repositories and include why they are different from this repo.

- [x] Invite other repos to contribute to include alt directory structures.

- [x] Move description and link to original blog article to bottom of README.md  The blog article is a long ways away from the repository now and I think should not be promoted before this new project

- [x] Move application screenshot below Demonstration Application in README.md  This would open up the README and push the link to the docs higher in the page.

- [x] Fix webhook for readthedocs integration

- [ ] Get docs from @mathisGarberg for #24

**Comment by TomHAnderson** [comment]
#24 was closed.
